server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/lease?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
    username: root
    password: Ljx123456
    hikari:
      connection-test-query: SELECT 1 # Auto connection
      connection-timeout: 60000 #Database connection timeout, default is 30 seconds
      idle-timeout: 500000 #Maximum idle timeout, default 600000
      max-lifetime: 540000
      maximum-pool-size: 12
      minimum-idle: 10
      pool-name: SPHHikariPool

#Print SQL Statement for adjustment
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl